receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu: {}
      memory: {}
      load: {}
      network: {}
  filelog:
    include: ["/logs/*.log"]
    include_file_name: false
    include_file_path: false
    operators:
      - type: json_parser
        timestamp:
          parse_from: attributes.time
          layout: "%Y-%m-%dT%H:%M:%S.%LZ"
      - type: move
        from: attributes.msg
        to: body
      - type: move
        from: attributes.service
        to: resource["service.name"]

processors:
  batch: {}
  resourcedetection:
    detectors: [env, system]

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
    resource_to_telemetry_conversion:
      enabled: true
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
  debug:
    verbosity: basic

service:
  telemetry:
    logs:
      level: info
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, resourcedetection]
      exporters: [otlp/tempo]
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [batch, resourcedetection]
      exporters: [prometheus]
    logs:
      receivers: [filelog]
      processors: [batch, resourcedetection]
      exporters: [loki, debug]
